# Cómo trabajar con matrices

In [1]:
import tensorflow as tf
session = tf.Session()

### 1. Cómo crear matrices

In [16]:
identity = tf.diag([1.,1.,1.,1.])
print(session.run(identity))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
A = tf.truncated_normal([3,4])
print(session.run(A))

[[ 0.23105556  0.14443368  0.18416359 -0.02203175]
 [ 1.0409501  -0.26933646  0.29310364  0.01460349]
 [ 0.34734637  0.12096282  0.5520747   1.8985133 ]]


In [11]:
B = tf.fill([3,4], 1988.)
print(session.run(B))

[[1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]]


In [9]:
C = tf.random_uniform([4,3])
print(session.run(C))

[[0.50415564 0.633165   0.7339585 ]
 [0.4802469  0.625553   0.6599302 ]
 [0.07117975 0.97317564 0.78740287]
 [0.43302882 0.69417155 0.6581012 ]]


In [7]:
import numpy as np
data = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
D = tf.convert_to_tensor(data)
print(session.run(D))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 2. Operar con matrices

In [12]:
print(session.run(A+B))

[[1988.3859 1989.2444 1988.7979 1987.9745]
 [1986.0353 1988.711  1987.7976 1987.404 ]
 [1988.4165 1987.4631 1988.9714 1989.6074]]


In [13]:
print(session.run(B-B))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
print(session.run(tf.matmul(A,C)))

[[-1.5698699  -1.5181621  -1.7350993 ]
 [ 1.840872    2.5496354   1.4434798 ]
 [-0.9077603  -0.5962755  -0.14483558]]


In [17]:
print(session.run(tf.matmul(A, identity)))

[[-0.00428006  0.53683907  0.28892404  0.06606133]
 [-0.8074294  -0.3064044  -0.40682808 -0.28900728]
 [-0.5137373  -1.9596008   0.16382343  0.32906753]]


## 3. Tranpuesta, determinante, inversa

In [18]:
print(session.run(tf.transpose(D)))

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [19]:
print(session.run(tf.transpose(A)))

[[-0.6396708  -0.5391506   0.01423284]
 [-0.5098239   0.67564106  1.2016957 ]
 [ 0.04176678 -1.4263176  -1.1400442 ]
 [ 0.75535095 -0.7316276   0.1967118 ]]


In [20]:
print(session.run(tf.matrix_determinant(D)))

6.66133814775094e-16


In [21]:
E = tf.convert_to_tensor(np.array([[1.,2.,3.], [-3., -6., -1], [0., 5, -3]]))
print(session.run(tf.matrix_determinant(E)))

-40.0


In [23]:
print(session.run(tf.matrix_inverse(E)))

[[-0.575 -0.525 -0.4  ]
 [ 0.225  0.075  0.2  ]
 [ 0.375  0.125  0.   ]]


## 4. Descomposición

In [25]:
print(session.run(tf.cholesky(identity)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 5. Valores y vectores propios

In [29]:
print(session.run(tf.self_adjoint_eigvals(E)))

[-10.24888536  -0.66882335   2.91770871]


In [30]:
print(session.run(tf.self_adjoint_eig(E)))

(array([-10.24888536,  -0.66882335,   2.91770871]), array([[ 0.21442787,  0.60489799, -0.76688924],
       [ 0.80402486,  0.3364893 ,  0.49022339],
       [-0.55458517,  0.72171557,  0.41420034]]))
