# Operaciones con TensorFlow

In [1]:
import tensorflow as tf
session = tf.Session()

### Operaciones aritméticas

In [2]:
x = 3
y = 4

In [3]:
print(session.run(tf.add(x,y)))

7


In [4]:
print(session.run(tf.subtract(x,y)))

-1


In [5]:
print(session.run(tf.multiply(x,y)))

12


In [6]:
print(session.run(tf.div(x,y)))

0


In [7]:
print(session.run(tf.truediv(x,y)))

0.75


In [8]:
print(session.run(tf.floordiv(7.0,3.0)))

2.0


In [9]:
print(session.run(tf.mod(23.0, 5.0)))

3.0


In [10]:
print(session.run(tf.cross([1.0,0.,0.], [0.,1.,0.])))

[0. 0. 1.]


## Funciones matemáticas

In [24]:
x = [-3.,-2.,-1.,0.,1.,2.]

In [25]:
print(session.run(tf.abs(x)))

[3. 2. 1. 0. 1. 2.]


In [27]:
print(session.run(tf.ceil(6.4)))

7.0


In [28]:
print(session.run(tf.floor(6.4)))

6.0


In [30]:
print(session.run(tf.round(6.6)))

7.0


In [31]:
print(session.run(tf.sin(x)))

[-0.14112    -0.9092974  -0.84147096  0.          0.84147096  0.9092974 ]


In [32]:
print(session.run(tf.cos(x)))

[-0.9899925  -0.41614684  0.5403023   1.          0.5403023  -0.41614684]


In [33]:
print(session.run(tf.tan(x)))

[ 0.14254655  2.1850398  -1.5574077   0.          1.5574077  -2.1850398 ]


In [34]:
print(session.run(tf.exp(x)))

[0.04978707 0.13533528 0.36787945 1.         2.7182817  7.389056  ]


In [35]:
print(session.run(tf.log(x)))

[      nan       nan       nan      -inf 0.        0.6931472]


In [39]:
y = [4., 3., 7., -4., -3., 7.]

In [40]:
print(session.run(tf.maximum(x,y)))

[4. 3. 7. 0. 1. 7.]


In [41]:
print(session.run(tf.minimum(x,y)))

[-3. -2. -1. -4. -3.  2.]


In [42]:
print(session.run(tf.negative(x)))

[ 3.  2.  1. -0. -1. -2.]


In [43]:
print(session.run(tf.pow(x, y)))

[ 81.  -8.  -1.  inf   1. 128.]


In [45]:
print(session.run(tf.sqrt(x)))

[      nan       nan       nan 0.        1.        1.4142135]


In [46]:
print(session.run(tf.rsqrt(x)))

[       nan        nan        nan        inf 1.         0.70710677]


In [48]:
print(session.run(tf.square(x)))

[9. 4. 1. 0. 1. 4.]


In [49]:
print(session.run(tf.sign(x)))

[-1. -1. -1.  0.  1.  1.]


## Otras funciones

In [50]:
print(session.run(tf.digamma(x)))

[       inf        inf        inf        inf -0.5772159  0.4227842]


In [52]:
print(session.run(tf.lbeta(x)))

nan


In [53]:
print(session.run(tf.lgamma(x)))

[inf inf inf inf  0.  0.]


In [54]:
print(session.run(tf.erf(x)))

[-0.9999779 -0.9953223 -0.8427008  0.         0.8427008  0.9953223]


In [55]:
print(session.run(tf.erfc(x)))

[1.999978   1.9953222  1.8427008  1.         0.1572992  0.00467773]


In [56]:
print(session.run(tf.squared_difference(x,y)))

[49. 25. 64. 16. 16. 25.]


In [58]:
print(session.run(tf.tan(3.14159265/4.)))

1.0


## Funciones propias

$$y = 5x^2-7x+15$$

In [59]:
def custom_parabola(value):
    return tf.subtract(5*tf.square(value), 7*value)+15

In [60]:
print(session.run(custom_parabola(5)))

105
