# Redes neuronales multicapas

### Ejemplo 1D 

In [2]:
import tensorflow as tf
import numpy as np
session = tf.Session()

In [3]:
data_size = 25
data_1d = np.random.normal(size = data_size)
x_input_1d = tf.placeholder(shape=[data_size], dtype=tf.float32)

In [6]:
def conv_layer_1d(input_1d, my_filter):
    input_2d = tf.expand_dims(input_1d, 0)
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    convolution = tf.nn.conv2d(input_4d, filter = my_filter, strides = [1,1,1,1], padding="VALID")
    output = tf.squeeze(convolution)
    return(output)

In [7]:
my_filter = tf.Variable(tf.random_normal(shape=[1,5,1,1]))
my_conv_output = conv_layer_1d(x_input_1d, my_filter)

In [8]:
def activation(input_1d):
    return tf.nn.relu(input_1d)
my_activation_output = activation(my_conv_output)

In [9]:
def max_pool(input_1d, width):
    input_2d = tf.expand_dims(input_1d, 0)
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    pooling = tf.nn.max_pool(input_4d, ksize=[1,1,width,1], strides=[1,1,1,1], padding="VALID")
    output = tf.squeeze(pooling)
    return(output)

In [10]:
my_maxpool_ouput = max_pool(my_activation_output, width=5)

In [11]:
def fully_connected(input_layer, num_output):
    weight_shape = tf.squeeze(tf.stack([tf.shape(input_layer), [num_output]]))
    weight = tf.random_normal(weight_shape, stddev=0.1)
    bias = tf.random_normal(shape=[num_output])
    input_layer_2d = tf.expand_dims(input_layer,0)
    full_output = tf.add(tf.matmul(input_layer_2d, weight), bias)
    full_output_1d = tf.squeeze(full_output)
    return(full_output_1d)

In [12]:
my_full_output = fully_connected(my_maxpool_ouput, 5)

In [13]:
init = tf.global_variables_initializer()
session.run(init)

In [14]:
feed_dict = {x_input_1d: data_1d}

In [16]:
data_1d

array([ 1.11726143,  1.2199282 ,  2.08403659, -0.5641956 , -1.97417837,
        0.74121749, -0.06573571,  0.68324515,  0.15140036, -1.47523627,
       -1.76683959,  0.29992843, -0.40987229, -2.27857269,  0.85453741,
        0.90486784, -0.83307896,  0.86211523, -0.72954449, -2.11379079,
        1.17546086, -1.09596305,  1.80804086, -0.27225049,  1.95735632])

In [17]:
session.run(my_filter)

array([[[[ 0.21220557]],

        [[-0.8410326 ]],

        [[-0.4553594 ]],

        [[ 1.3882189 ]],

        [[ 1.3427733 ]]]], dtype=float32)

In [15]:
# Operación de convolución
print("Input: tamaño 25, Operación: convolución con filtro de tamaño 5 + stride de tamaño 1, Resultado: tamaño 21")
print(session.run(my_conv_output, feed_dict=feed_dict))

Input: tamaño 25, Operación: convolución con filtro de tamaño 5 + stride de tamaño 1, Resultado: tamaño 21
[-5.171997   -2.9822598   2.7564158   2.0292904   0.13940382 -1.8692768
 -5.0779386  -1.360606    1.9433976  -2.592258   -2.4562511   3.8472493
  1.5777737  -1.6131305   0.01685643 -3.3510168  -1.9256727   1.9192178
  1.9940488   1.2062836   2.5982141 ]


In [18]:
# Función de activación
print("Input: tamaño 21, Operación: ReLU al array anterior, Resultado: tamaño 21")
print(session.run(my_activation_output, feed_dict=feed_dict))

Input: tamaño 21, Operación: ReLU al array anterior, Resultado: tamaño 21
[0.         0.         2.7564158  2.0292904  0.13940382 0.
 0.         0.         1.9433976  0.         0.         3.8472493
 1.5777737  0.         0.01685643 0.         0.         1.9192178
 1.9940488  1.2062836  2.5982141 ]


In [19]:
# Operción de Max Pooling
print("Input: tamaño 21, Operación: maxpooling con ventana de tamaño 5 + stride de tamaño 1, Resultado: tamaño 17")
print(session.run(my_maxpool_ouput, feed_dict=feed_dict))

Input: tamaño 21, Operación: maxpooling con ventana de tamaño 5 + stride de tamaño 1, Resultado: tamaño 17
[2.7564158 2.7564158 2.7564158 2.0292904 1.9433976 1.9433976 1.9433976
 3.8472493 3.8472493 3.8472493 3.8472493 3.8472493 1.5777737 1.9192178
 1.9940488 1.9940488 2.5982141]


In [20]:
# Capa Totalmente Conectada
print("Input: tamaño 17, Operación de conectar totalmente la entrada con 5 valores de salida, Resultado: tamaño 5")
print(session.run(my_full_output, feed_dict=feed_dict))

Input: tamaño 17, Operación de conectar totalmente la entrada con 5 valores de salida, Resultado: tamaño 5
[-0.36904252  0.5647052  -1.968683   -0.60227275 -0.5455638 ]


### Ejemplo 2D

In [21]:
session = tf.Session()

In [22]:
data_size = [10,10]
data_2d = np.random.normal(size = data_size)
x_input_2d = tf.placeholder(dtype=tf.float32, shape=data_size)

In [23]:
def conv_layer_2d(input_2d, my_filter):
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    convolution = tf.nn.conv2d(input_4d, filter=my_filter, strides = [1,2,2,1], padding="VALID")
    output = tf.squeeze(convolution)
    return(output)

In [24]:
my_filter = tf.Variable(tf.random_normal(shape=[2,2,1,1]))
my_conv_output = conv_layer_2d(x_input_2d, my_filter)

In [25]:
def activation(input_2d):
    return(tf.nn.relu(input_2d))

In [26]:
my_activation_output = activation(my_conv_output)

In [27]:
def max_pool(input_2d, width, height):
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    pooling = tf.nn.max_pool(input_4d, ksize=[1,height,width,1], strides=[1,1,1,1], padding="VALID")
    output = tf.squeeze(pooling)
    return(output)

In [28]:
my_maxpool_ouput = max_pool(my_activation_output, width=2, height=2)

In [29]:
def fully_connected(input_layer, num_output):
    flat_input = tf.reshape(input_layer, [-1])
    weight_shape = tf.squeeze(tf.stack([tf.shape(flat_input), [num_output]]))
    weight = tf.random_normal(weight_shape, stddev=0.1)
    bias = tf.random_normal(shape=[num_output])
    input_layer_2d = tf.expand_dims(flat_input,0)
    full_output = tf.add(tf.matmul(input_layer_2d, weight), bias)
    full_output_1d = tf.squeeze(full_output)
    return(full_output_1d)

In [30]:
my_full_output = fully_connected(my_maxpool_ouput, 5)

In [31]:
init = tf.global_variables_initializer()
session.run(init)

In [32]:
feed_dict = {x_input_2d: data_2d}

In [33]:
data_2d

array([[ 2.00794069e+00,  8.14974415e-01,  3.99545355e-01,
        -9.99935947e-01,  1.13843544e+00, -1.58561486e+00,
         1.69878991e+00,  1.27893390e+00, -4.94362725e-01,
         6.88226682e-01],
       [ 9.10593947e-01, -8.34740805e-01,  1.01465504e+00,
         8.26075158e-01,  2.68018976e-02, -1.25803966e+00,
         2.20600669e+00, -4.71856405e-01,  2.81416120e+00,
         6.67204146e-01],
       [ 1.17116723e+00,  8.27132156e-01, -5.76934334e-01,
         1.52032004e+00,  1.10693142e-01, -5.51934746e-01,
        -2.36690741e-01,  2.50897165e-01,  1.67329665e-01,
        -4.12898991e-01],
       [ 5.70793910e-01,  1.14080357e+00,  1.28673527e+00,
        -8.07325421e-02, -3.20146727e-02, -2.00174601e-01,
         2.28607480e-01, -1.31197492e+00, -1.46031949e+00,
         2.00770654e-01],
       [ 2.06144033e+00, -1.84161198e+00, -1.82910346e+00,
        -1.87444295e+00,  1.26099042e+00,  4.47116593e-01,
        -1.98763105e-01,  1.22677526e+00, -1.04526586e+00,
         7.

In [35]:
session.run(my_filter)

array([[[[-0.81051064]],

        [[-1.3463479 ]]],


       [[[ 0.74122626]],

        [[-0.68318665]]]], dtype=float32)

In [36]:
# Operación de convolución
print("Input: tamaño 10x10, Operación: convolución con filtro de tamaño 2x2 + stride de tamaño 2x2, Resultado: tamaño 5x5")
print(session.run(my_conv_output, feed_dict=feed_dict))

Input: tamaño 10x10, Operación: convolución con filtro de tamaño 2x2 + stride de tamaño 2x2, Resultado: tamaño 5x5
[[-1.4794567   1.2101513   2.0914173  -1.1412611   1.104199  ]
 [-2.4191456  -0.570351    0.7664047   0.9198191  -0.79930776]
 [ 2.7884169   4.9690366  -0.5625584  -1.6185242  -0.03134565]
 [-3.594647   -1.8339328  -0.6067862  -1.3250389   0.11603214]
 [-1.0607617  -4.186264   -0.80572134  0.18619394 -1.7206349 ]]


In [37]:
# Función de activación
print("Input: tamaño 5x5, Operación: ReLU al array anterior, Resultado: tamaño 5x5")
print(session.run(my_activation_output, feed_dict=feed_dict))

Input: tamaño 5x5, Operación: ReLU al array anterior, Resultado: tamaño 5x5
[[0.         1.2101513  2.0914173  0.         1.104199  ]
 [0.         0.         0.7664047  0.9198191  0.        ]
 [2.7884169  4.9690366  0.         0.         0.        ]
 [0.         0.         0.         0.         0.11603214]
 [0.         0.         0.         0.18619394 0.        ]]


In [39]:
# Operción de Max Pooling
print("Input: tamaño 5x5, Operación: maxpooling con ventana de tamaño 2x2 + stride de tamaño 1, Resultado: tamaño 4x4")
print(session.run(my_maxpool_ouput, feed_dict=feed_dict))

Input: tamaño 5x5, Operación: maxpooling con ventana de tamaño 2x2 + stride de tamaño 1, Resultado: tamaño 4x4
[[1.2101513  2.0914173  2.0914173  1.104199  ]
 [4.9690366  4.9690366  0.9198191  0.9198191 ]
 [4.9690366  4.9690366  0.         0.11603214]
 [0.         0.         0.18619394 0.18619394]]


In [40]:
# Capa Totalmente Conectada
print("Input: tamaño 4x4, Operación de conectar totalmente la entrada con 5 valores de salida, Resultado: tamaño 5")
print(session.run(my_full_output, feed_dict=feed_dict))

Input: tamaño 4x4, Operación de conectar totalmente la entrada con 5 valores de salida, Resultado: tamaño 5
[-3.1488183 -0.9166634  0.6182389 -1.320861   0.6795198]
