# Distancia de Levenshtein

$x,y\in S$ donde $S$ es el conjunto de Strings, entonces $d(x,y)$ se define como el número de operaciones (ediciones) para convertir la palabra $x$ en la palabra $y$, donde las ediciones posibles de la palabra son:
- insertar un nuevo caracter
- eliminar un caracter de la palabra
- sustituir un caracter por otro

In [18]:
import tensorflow as tf
session = tf.Session()

In [4]:
hypothesis = list('casa')
truth = list('calle')

In [5]:
h1 = tf.SparseTensor([[0,0,0], [0,0,1], [0,0,2], [0,0,3]],
                    hypothesis, [1,1,1])
t1 = tf.SparseTensor([[0,0,0], [0,0,1], [0,0,2], [0,0,3], [0,0,4]],
                    truth, [1,1,1])

In [8]:
print(session.run(tf.edit_distance(h1, t1, normalize=False)))

[[3.]]


In [9]:
print(session.run(tf.edit_distance(h1, t1, normalize=True)))

[[0.6]]


In [11]:
session.run(h1)

SparseTensorValue(indices=array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 0, 3]]), values=array([b'c', b'a', b's', b'a'], dtype=object), dense_shape=array([1, 1, 1]))

In [12]:
hypothesis2 = list('casacalle')
truth2 = list('callescalles')

In [17]:
h2 = tf.SparseTensor([[0,0,0], [0,0,1], [0,0,2], [0,0,3], [0,1,0], [0,1,1], [0,1,2],[0,1,3],[0,1,4]],
                    hypothesis2, [1,2,4])
t2 = tf.SparseTensor([[0,0,0], [0,0,1],[0,0,2],[0,0,3],[0,0,4], [0,0,5], 
                      [0,1,0],[0,1,1],[0,1,2],[0,1,3],[0,1,4],[0,1,5]],
                    truth2, [1,2,6])

In [18]:
print(session.run(tf.edit_distance(h2,t2,normalize=False)))

[[4. 1.]]


In [19]:
print(session.run(tf.edit_distance(h2,t2,normalize=True)))

[[0.6666667  0.16666667]]


In [19]:
hypothesis_words = ["casa", "casita", "caseron", "tensor", "python"]
truth_word = "algoritmo"

In [20]:
num_h_words = len(hypothesis_words)
h_idx = [[xi,0,yi] for xi,x in enumerate(hypothesis_words) for yi,y in enumerate(x)]
h_idx

[[0, 0, 0],
 [0, 0, 1],
 [0, 0, 2],
 [0, 0, 3],
 [1, 0, 0],
 [1, 0, 1],
 [1, 0, 2],
 [1, 0, 3],
 [1, 0, 4],
 [1, 0, 5],
 [2, 0, 0],
 [2, 0, 1],
 [2, 0, 2],
 [2, 0, 3],
 [2, 0, 4],
 [2, 0, 5],
 [2, 0, 6],
 [3, 0, 0],
 [3, 0, 1],
 [3, 0, 2],
 [3, 0, 3],
 [3, 0, 4],
 [3, 0, 5],
 [4, 0, 0],
 [4, 0, 1],
 [4, 0, 2],
 [4, 0, 3],
 [4, 0, 4],
 [4, 0, 5]]

In [21]:
h_chars = list(''.join(hypothesis_words))
h_chars

['c',
 'a',
 's',
 'a',
 'c',
 'a',
 's',
 'i',
 't',
 'a',
 'c',
 'a',
 's',
 'e',
 'r',
 'o',
 'n',
 't',
 'e',
 'n',
 's',
 'o',
 'r',
 'p',
 'y',
 't',
 'h',
 'o',
 'n']

In [22]:
h3 = tf.SparseTensor(h_idx, h_chars, [num_h_words, 1, 1])

In [23]:
truth_word_vect = [truth_word]*num_h_words
truth_word_vect

'algoritmoalgoritmoalgoritmoalgoritmoalgoritmo'

In [26]:
t_idx = [[xi,0,yi] for xi,x in enumerate(truth_word_vect) for yi, y in enumerate(x)]
t_idx

[[0, 0, 0],
 [0, 0, 1],
 [0, 0, 2],
 [0, 0, 3],
 [0, 0, 4],
 [0, 0, 5],
 [0, 0, 6],
 [0, 0, 7],
 [0, 0, 8],
 [1, 0, 0],
 [1, 0, 1],
 [1, 0, 2],
 [1, 0, 3],
 [1, 0, 4],
 [1, 0, 5],
 [1, 0, 6],
 [1, 0, 7],
 [1, 0, 8],
 [2, 0, 0],
 [2, 0, 1],
 [2, 0, 2],
 [2, 0, 3],
 [2, 0, 4],
 [2, 0, 5],
 [2, 0, 6],
 [2, 0, 7],
 [2, 0, 8],
 [3, 0, 0],
 [3, 0, 1],
 [3, 0, 2],
 [3, 0, 3],
 [3, 0, 4],
 [3, 0, 5],
 [3, 0, 6],
 [3, 0, 7],
 [3, 0, 8],
 [4, 0, 0],
 [4, 0, 1],
 [4, 0, 2],
 [4, 0, 3],
 [4, 0, 4],
 [4, 0, 5],
 [4, 0, 6],
 [4, 0, 7],
 [4, 0, 8]]

In [27]:
t_chars = list(''.join(truth_word_vect))

In [28]:
t3 = tf.SparseTensor(t_idx, t_chars, [num_h_words,1,1])

In [29]:
print(session.run(tf.edit_distance(h3, t3, normalize=False)))

[[9.]
 [7.]
 [8.]
 [8.]
 [8.]]


In [30]:
print(session.run(tf.edit_distance(h3, t3, normalize=True)))

[[1.       ]
 [0.7777778]
 [0.8888889]
 [0.8888889]
 [0.8888889]]


In [31]:
def create_sparse_words_vect(word_list):
    num_words = len(word_list)
    idx = [[xi,0,yi] for xi,x in enumerate(word_list) for yi, y in enumerate(x)]
    chars = list(''.join(word_list))
    return tf.SparseTensorValue(idx, chars, [num_words, 1, 1])

In [39]:
hyp_string_sp = create_sparse_words_vect(hypothesis_words)
tr_string_sp = create_sparse_words_vect([truth_word]*len(hypothesis_words))

In [40]:
h_input = tf.sparse_placeholder(dtype=tf.string)
t_input = tf.sparse_placeholder(dtype=tf.string)

In [41]:
edit_distance = tf.edit_distance(h_input, t_input, normalize=True)

In [42]:
feed_dict = {h_input:hyp_string_sp, t_input:tr_string_sp}

In [43]:
print(session.run(edit_distance, feed_dict=feed_dict))

[[1.       ]
 [0.7777778]
 [0.8888889]
 [0.8888889]
 [0.8888889]]


# Otras distancias para comparar palabras

### Distancia de Hamming
- Número de caracteres iguales en la misma posición. 
- Las dos palabras deben ser de la misma longitud
$$D(s_1,s_2) = \sum_{i=1}^n I_i$$
donde $I_i=1$ si las dos palabras tienen el mismo caracter en la posición i-ésima  y 0 en otro caso

### Distancia del Coseno
- Obtenemos el producto escalar del vector de k-gramas de cada palabra dividida por la norma dos de los mismos
$$D(s_1,s_2) = 1 - \frac{k(s_1)\cdot k(s_2)}{||k(s_1)||||k(s_2)||}$$

### Distancia de Jaccard
- Numero de caracteres en común entre las dos palabras dividido por la unión total de caracteres de ambas palabras
$$D(s_1,s_2) = \frac{|s_1\cap s_2|}{|s_1\cup s_2|}$$